### ISSUE TITLE
Quarkiverse Extension

### ISSUE THREAD

**Issue by melloware** [mostafacs/quarkus-temporal-demo#1]
@mostafacs does this plugin work with Quarkus?

Any interest in making it a Quarkiverse extension: https://github.com/quarkusio/quarkus/issues/42358

**Comment by mostafacs** [comment]
@melloware Yes - The plugin is working with Quarkus. We are using it in my current working company. I can add it to Quarkiverse by the end of the year. Thanks!

**Comment by melloware** [comment]
@mostafacs we already have this project we started https://github.com/quarkiverse/quarkus-temporal  we would love it f you would join us.  We are having trouble making Native mode work.  We saw your Netty Shaded processor but you can see from our CI/CD its still not working...

https://github.com/quarkiverse/quarkus-temporal/actions/runs/10325072740/job/28585905932

We have a Dev UI Card and are planning on trying to make Temporal work as a Dev Service as well.

![image](https://github.com/user-attachments/assets/5740ff9e-31d9-4fdd-a6a4-b2c958ab8603)

**Comment by melloware** [comment]
Update we have advanced our extension very far including OpenTelemetry support and MDC propagation.
